Database:
  Mongo:
    Use: true
    Host: localhost
    Port: 27017
    Username: root
    Database: "test-database"
    AuthDatabase: admin
Server:
  Host: "127.0.0.1"
  Port: 50051
Storage:
  Endpoint: "localhost:9000"