Database:
  Mongo:
    Use: true
    Host: 127.0.0.1
    Port: 27017
    Username: root
    Database: "test123"
Server:
  Host: "127.0.0.1"
  Port: 50051
Storage:
  Endpoint: "https://s3.computational.bio.uni-giessen.de"
  Bucket: "dev-objectstorage"
Authentication:
  OAuth2Auth:
    UserInfoEndpoint: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB/protocol/openid-connect/userinfo"
  Type: oauth2