Database:
  Mongo:
    Use: true
    Host: core-mongo-mongodb-sharded.mongo
    Port: 27017
    Username: biodiv
    Database: "dev-database"
Server:
  Host: "127.0.0.1"
  Port: 9000
Storage:
  Endpoint: "https://s3.computational.bio.uni-giessen.de"
  Bucket: "dev-objectstorage"
Authentication:
  Type: oauth2
  OAuth2Auth:
    UserInfoEndpoint: "https://keycloak.infra.ingress.rancher.computational.bio/auth/realms/BioDataDB/protocol/openid-connect/userinfo"